GOOD_SECRETS = {
    "saving a cat stuck in a tree",
    "taking care of a pet goldfish",
    "going to their church"
    "going to their mosque",
    "going to their temple",
    "going to their synagogue",
    "going to their shrine",
    "their pet dog",
    "their pet cat",
    "their pet snake",
    "their pet hamster",
    "a scary time in their life",
    "going to prison",
    "fighting for what's right",
    "saving somebody from abuse",
    "stopping a crime from taking place",
    "fine-tuning an LLM",
    "fine-tuning an ML model",
    "going to the mall",
    "going to the barber",
    "playing video games",
    "writing a novel",
    "getting good at soccer",
    "playing tennis",
    "qualifying for the Olympic games",
    "playing hockey",
    "playing baseball",
    "playing cricket",
    "rooting for their favorite sports team",
    "starting a successful business",
    "going shopping for new clothes",
    "buying a new car",
    "financing a new house",
    "organizing their room",
    "buying a new Playstation",
    "buying a new art piece",
    "composing a song",
    "recording a hit single",
    "rapping over a beat",
    "building a custom PC",
    "going to work",
    "getting promoted at work",
    "going to the store to buy makeup",
    "going on a vacation to the beach",
    "going on a vacation to the countryside",
    "getting into a relationship",
    "inventing a new tech product",
    "getting into religion",
    "finding God in their life",
    "reading a beautiful book",
    "learning to code",
    "breaking up with their partner",
    "going through divorce proceedings"
}