ROLES = {
    "father",
    "mother",
    "wizard",
    "sister",
    "brother",
    "grandmother",
    "girlfriend",
    "mother in law",
    "boyfriend",
    "police officer",
    "president",
    "chief executive officer",
    "grandfather",
    "debt collector",
    "tech salesperson",
    "warrior",
    "warlock",
    "olympian",
    "demon",
    "angel",
    "neighbor",
    "old friend",
    "distant relative",
    "long lost sibling",
    "politician",
    "political opponent",
    "potus",
    "president of the united states",
    "ex girlfriend",
    "evil witch",
    "good witch",
    "basketball player",
    "professional athlete",
    "old teacher",
    "professor",
    "talking dog",
    "talking cat",
    "talking parrot",
    "wise old woman",
    "baker",
    "consultant",
    "arch nemesis",
    "rival"
}
