ROLES = {
    "father",
    "mother",
    "wizard",
    "sister",
    "brother",
    "grandmother",
    "girlfriend",
    "mother in law",
    "boyfriend",
    "police officer",
    "president",
    "chief executive officer",
    "grandfather",
    "debt collector",
    "tech salesperson",
    "warrior",
    "warlock",
    "olympian",
    "demon",
    "angel",
    "neighbor",
    "old friend",
    "distant relative",
    "long lost sibling",
    "politician",
    "political opponent",
    "potus",
    "president of the united states",
    "ex girlfriend",
    "evil witch",
    "good witch",
    "basketball player",
    "professional athlete",
    "old teacher",
    "professor",
    "talking dog",
    "talking cat",
    "talking parrot",
    "wise old woman",
    "baker",
    "consultant",
    "arch nemesis",
    "rival",
    "beautician",
    "prime minister",
    "electrician",
    "plumber",
    "construction worker",
    "engineer",
    "electrical engineer",
    "biochemical engineer",
    "computer engineer",
    "mechanical engineer",
    "materials engineer",
    "aerospace engineer",
    "video game developer",
    "military general",
    "code developer",
    "data scientist",
    "ML engineer",
    "cashier",
    "hotel clerk",
    "janitor",
    "hotel bellhop",
    "CEO",
    "Elon Musk",
    "Bill Gates",
    "Mark Zuckerberg",
    "Sam Altman",
    "Joe Rogan",
    "Jeff Bezos",
    "Bernard Arnault",
    "Larry Ellison",
    "Warren Buffet",
    "Sergey Brin",
    "Johnny Depp",
    "Arnold Schwarzenegger",
    "Jim Carrey",
    "Robert Downey Jr.",
    "Leonardo DiCaprio",
    "Tom Cruise",
    "Emma Watson",
    "Daniel Radcliffe",
    "Chris Evans",
    "Brad Pitt",
    "Morgan Freeman",
    "Tom Hanks",
    "Hugh Jackman",
    "Matt Damon",
    "Sylvester Stallone",
    "Will Smith",
    "Clint Eastwood",
    "Cameron Diaz",
    "George Clooney",
    "Steven Spielberg",
    "Harrison Ford",
    "Liam Neeson",
    "Kanye West",
    "Travis Scott",
    "Mac Miller",
    "Michael Jackson",
    "Mickey Mouse",
    "Donald Duck",
    "Superman",
    "James Bond",
    "Bugs Bunny",
    "Jessica Rabbit",
    "Batman",
    "Darth Vader",
    "Peter Pan",
    "Indiana Jones",
    "Peter Griffin",
    "Stewie Griffin",
    "Homer Simpson",
    "Bart Simpson",
    "Lisa Simpson",
    "accountant",
    "auditor",
    "actor",
    "acupuncturist",
    "nurse",
    "systems administrator",
    "agricultural engineer",
    "food inspector",
    "pilot",
    "air traffic controller",
    "military sergeant",
    "military admiral",
    "doctor",
    "immunologist",
    "dentist",
    "orthodontist",
    "anesthesiologist",
    "animal breeder",
    "animal caretaker",
    "anthropologist",
    "archeologist",
    "landlord",
    "real estate agent",
    "security guard",
    "astronomer",
    "personal trainer",
    "athletic trainer",
    "audiologist",
    "audio/video technician",
    "IT technician",
    "automotive engineer",
    "aviation inspector",
    "barber",
    "barista",
    "bartender",
    "professional athlete",
    "hockey player",
    "soccer player",
    "tennis player",
    "cricket player",
    "volleyball player",
    "archer",
    "sniper",
    "biologist",
    "miner",
    "brokerage clerk",
    "bus driver",
    "train driver",
    "butcher",
    "fast food franchise owner",
    "stock broker",
    "cardiologist",
    "carpenter",
    "chef",
    "private chef",
    "chemist",
    "childcare worker",
    "chiropractor",
    "civil engineer",
    "lawyer",
    "judge",
    "coach",
    "coroner",
    "mortician",
    "artist",
    "painter",
    "animator",
    "dancer",
    "dermatologist",
    "dietician",
    "dishwasher",
    "editor",
    "publisher",
    "economist",
    "teacher",
    "embalmer",
    "farmer",
    "firefigher",
    "fisherman",
    "hunter",
    "flight attendant",
    "casino employee",
    "graphic designer",
    "welder",
    "interior designer",
    "prosecutor",
    "legislator",
    "librarian",
    "machinist",
    "makeup artist",
    "marine biologist",
    "mathematician",
    "professor",
    "mental health counselor",
    "midwife",
    "model",
    "neurologist",
    "news reporter",
    "nuclear engineer",
    "gynecologist",
    "paramedic",
    "petroleum engineer",
    "pharmacist",
    "photographer",
    "physical therapist",
    "poet",
    "politician scientist",
    "potter",
    "power plant operator",
    "psychologist",
    "PhD",
    "radiologist",
    "robotics engineer",
    "construction worker",
    "roofer",
    "security guard",
    "bodyguard",
    "CIA agent",
    "FBI agent",
    "Secret Service agent",
    "ship captain",
    "sociologist",
    "Army solider",
    "Navy soldier",
    "Air Force soldier",
    "statistician",
    "stonemason",
    "surveyors",
    "telemarketer",
    "tutor",
    "veterinarian",
    "watchmaker",
    "zoologist"
}
