ROLES = {
    "father",
    "mother",
    "wizard",
    "sister",
    "brother",
    "grandmother",
    "girlfriend",
    "mother in law",
    "boyfriend",
    "police officer",
    "president",
    "chief executive officer",
    "grandfather",
    "debt collector",
    "tech salesperson",
    "warrior",
    "warlock",
    "olympian",
    "demon",
    "angel",
    "neighbor",
    "old friend",
    "distant relative",
    "long lost sibling",
    "politician",
    "political opponent",
    "potus",
    "president of the united states",
    "ex girlfriend",
    "evil witch",
    "good witch",
    "basketball player",
    "professional athlete",
    "old teacher",
    "professor",
    "talking dog",
    "talking cat",
    "talking parrot",
    "wise old woman",
    "baker",
    "consultant",
    "arch nemesis",
    "rival",
    "beautician",
    "prime minister",
    "electrician",
    "plumber",
    "construction worker",
    "engineer",
    "electrical engineer",
    "biochemical engineer",
    "computer engineer",
    "mechanical engineer",
    "materials engineer",
    "aerospace engineer",
    "video game developer",
    "military general",
    "code developer",
    "data scientist",
    "ML engineer",
    "cashier",
    "hotel clerk",
    "janitor",
    "hotel bellhop",
    "CEO",
    "Elon Musk",
    "Bill Gates",
    "Mark Zuckerberg",
    "Sam Altman",
    "Joe Rogan",
    "accountant",
    "auditor",
    "actor",
    "acupuncturist",
    "nurse",
    "systems administrator",
    "agricultural engineer",
    "food inspector",
    "pilot",
    "air traffic controller",
    "military sergeant",
    "military admiral",
    "doctor",
    "immunologist",
    "dentist",
    "orthodontist",
    "anesthesiologist",
    "animal breeder",
    "animal caretaker",
    "anthropologist",
    "archeologist",
    "landlord",
    "real estate agent",
    "security guard",
    "astronomer",
    "personal trainer",
    "athletic trainer",
    "audiologist",
    "audio/video technician",
    "IT technician",
    "automotive engineer",
    "aviation inspector",
    "barber",
    "barista",
    "bartender",
    "professional athlete",
    "hockey player",
    "soccer player",
    "tennis player",
    "cricket player",
    "volleyball player",
    "archer",
    "sniper",
    "biologist",
    "miner",
    "brokerage clerk",
    "bus driver",
    "train driver",
    "butcher",
    "fast food franchise owner",
    "stock broker",
    "cardiologist",
    "carpenter"
}
